Add `!pom.xml`
Almighty-Alpaca/JDA-Butler pull request #6
Opened 2017-03-27 16:51 UTC by ArsenArsen

Adds `!pom.xml`

2017-03-27 17:13 UTC, MinnDevelopment commented on src/main/resources/maven.pom
> +                            <mainClass>YourMainClass</mainClass>
maybe put a comment here saying `You have to replace this with a path to your main class like my.path.Main` or something similar

2017-04-18 20:22 UTC, MinnDevelopment requested changes

2017-04-18 20:22 UTC, MinnDevelopment commented on build.gradle
> +	compile group: 'net.dv8tion', name: 'JDA', version: '3.0.0_163'
update

2017-04-18 20:45 UTC, Almighty-Alpaca approved these changes

2017-04-18 20:47 UTC, MinnDevelopment approved these changes

2017-04-18 20:47 UTC, merged